spring:
  datasource:
    url: jdbc:h2:mem:account_tx_db
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PWD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  jackson:
    default-property-inclusion: NON_EMPTY

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    disable-swagger-default-url: true

server:
  port: ${PORT:7981}



logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}
